### ISSUE TITLE
Support PHP 7.1

### ISSUE THREAD

**Issue by bobbingwide** [bobbingwide/oik-plugins#11]
When run under PHP 7.1 visiting wp-admin/edit.php?post_type=oik_pluginversion
leads to a blank area where the list of plugin versions should be.
It works in PHP 7.0

The problem applies to both oik_pluginversions and oik_premiumversions

### Actual output
```
Uncaught ArgumentCountError: 
Too few arguments to function oik_pluginversion_columns(), 
1 passed in wp-includes\class-wp-hook.php on line 298 and exactly 2 expected in 
wp-content\plugins\oik-plugins\oik-plugins.php:397
Stack trace:
#0 wp-includes\class-wp-hook.php(298): oik_pluginversion_columns(Array)
#1 wp-includes\plugin.php(203): WP_Hook-&gt;apply_filters(Array, Array)
#2 wp-admin\includes\screen.php(39): apply_filters('manage_edit-oik...', Array)
#3 wp-admin\includes\class-wp-screen.php(912): get_column_headers(Object(WP_Screen))
#4 wp-admin\includes\class-wp-screen.php(877): WP_Screen-&gt;show_screen_options()
#5 wp-admin\admin-header.php(233): WP_Screen-&gt;render_screen_meta()
#6 wp-admin\edit.php(303): require_once('C:\\apache\\htdoc...')
#7 {main}
```

**Comment by bobbingwide** [comment]
Solution is to change the add_filter() for "manage_edit-${post_type}-columns" to tell it to pass one parameter (not two ) and to change the filter hook to accept just one.

**Comment by bobbingwide** [comment]
oik-plugins v1.21.0 supports PHP 8.0. Closing this therefore
